name: "Phase 5: Merge"
on:
  status: {}
  check_run:
    types: [completed]

jobs:
  auto_merge:
    if: ${{ github.event.check_run.name == 'CL Runner' && github.event.check_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Auto Merge
        run: |
          echo "Merging into main..."
